project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  announcement: 
    icon: tools
    dismissable: true
    content: "**Under construction** - this workshop is complete but in beta test phase"
    type: info
    position: below-navbar
  site-url: index.qmd
  favicon: "images/bioDSC-without-dots-transparent.png"
  page-navigation: true
  sidebar:
    search: false
    id: main
    logo: "/images/bioDSC-without-dots-transparent.png"
    title: bioDSC RNA-seq
    style: "docked"
    background: primary
    foreground: light
    contents: episodes/*

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    grid:
      sidebar-width: 250px
      gutter-width: 3.5em
    
